name = "mostbetlogin-cz"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=mostbetlogin.cz"
HMAC_KEY = "a87ec55641b72fc4ea91885dc8dc2d9af80d1f116b9b5f2cd88678e26431bad6"
COOKIE_NAME = "hr5"
PLAY_PATH = "launch"
BUTTON_ID = "p8ab8b53d53d3dca395b4e40d490b48b2"
GATE_SALT = "f1ceb71c26acd09e"
